services:
  - type: web
    name: nexus-website
    env: static
    buildCommand: NODE_OPTIONS="--max-old-space-size=1024" npm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 18
